### ISSUE TITLE
A question about the 6th Equation in the paper

### ISSUE THREAD

**Issue by ConnollyLeon** [zhuohan123/terapipe#51]
Dear Sir,

I notice that in your paper, there is an equation: 

t_{fwd} (i, j) = t_{fwd}(i, 0) + t_{ctx}(i, j), 

Let j=0,  the second term will become zero.

But then we will have t_{ctx}(i, 0) = a_0  + a_1*i =0, which means that we don't need a_0 and a_1 at all. Or it means a_0, a_1 and i have a relation while a_0 and a_1 are constant and  i is variable. This is wrong unless a_0 and a_1 are zero.

I am not sure  if there is any restrictions on using this formula.

**Comment by zhuohan123** [comment]
You are right with the case where j=0. However, including these two terms is beneficial for modeling the performance of j > 0 (i.e. making them more accurate). We optimize this simple performance model to minimize the overall error. A more complicated performance should provide a better solution, but the current simple model works pretty well to find a good slicing scheme.

**Comment by ConnollyLeon** [comment]
Thanks for your reply.
